services:
  - type: web
    name: product-assistant
    env: docker
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: ASTRA_DB_API_ENDPOINT
        sync: false
      - key: ASTRA_DB_APPLICATION_TOKEN
        sync: false
      - key: ASTRA_DB_KEYSPACE
        sync: false
