services:
  - type: web
    name: product-assistant
    env: docker
    plan: free
    startCommand: bash -c "python -m prod_assistant.mcp_servers.product_search_server & uvicorn prod_assistant.router.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: ASTRA_DB_API_ENDPOINT
        sync: false
      - key: ASTRA_DB_APPLICATION_TOKEN
        sync: false
      - key: ASTRA_DB_KEYSPACE
        sync: false
